# Generated by Django 4.1.7 on 2023-02-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ('name',), 'verbose_name': 'Musician', 'verbose_name_plural': 'Musicians'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.musician', verbose_name='Musician name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='catalog.Membership', to='catalog.song', verbose_name='Song name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(verbose_name='Year of release'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Sequential number in the album'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songinalbum', to='catalog.song', verbose_name='Song name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Musician name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Song name'),
        ),
    ]
